#!/usr/bin/env python3
"""
DICOM Validation Script for dicom-converter-api

Validates DICOM files generated by the dicom-converter-api API against the DICOM standard
using pydicom. Checks mandatory tags, SOP class conformance, transfer syntax,
and encapsulation correctness.

Usage:
    python3 validate_dicom.py <dicom_file> [--type image|pdf|cda|stl]
    python3 validate_dicom.py --test-server <base_url>
"""

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

try:
    import pydicom
    from pydicom.uid import UID
except ImportError:
    print("ERROR: pydicom is required. Install with: pip install pydicom")
    sys.exit(1)


# Expected SOP Class UIDs
SOP_SECONDARY_CAPTURE = "1.2.840.10008.5.1.4.1.1.7"
SOP_ENCAPSULATED_PDF = "1.2.840.10008.5.1.4.1.1.104.1"
SOP_ENCAPSULATED_CDA = "1.2.840.10008.5.1.4.1.1.104.2"
SOP_ENCAPSULATED_STL = "1.2.840.10008.5.1.4.1.1.104.3"
SOP_VL_PHOTOGRAPHIC = "1.2.840.10008.5.1.4.1.1.77.1.4"
SOP_NEW_SC_CLASSES = [
    "1.2.840.10008.5.1.4.1.1.7.1",  # Multi-frame Single Bit
    "1.2.840.10008.5.1.4.1.1.7.2",  # Multi-frame Grayscale Byte
    "1.2.840.10008.5.1.4.1.1.7.3",  # Multi-frame Grayscale Word
    "1.2.840.10008.5.1.4.1.1.7.4",  # Multi-frame True Color
]


class DICOMValidator:
    """Validates DICOM files for standard compliance."""

    def __init__(self, filepath: str):
        self.filepath = filepath
        self.ds = None
        self.results = []
        self.passed = 0
        self.failed = 0

    def check(self, name: str, condition: bool, detail: str = ""):
        """Record a validation check result."""
        status = "PASS" if condition else "FAIL"
        if condition:
            self.passed += 1
        else:
            self.failed += 1
        self.results.append((name, status, detail))

    def load(self) -> bool:
        """Load the DICOM file."""
        try:
            self.ds = pydicom.dcmread(self.filepath)
            self.check("File Readable", True, f"Loaded {self.filepath}")
            return True
        except Exception as e:
            self.check("File Readable", False, str(e))
            return False

    def validate_file_meta(self):
        """Validate File Meta Information header."""
        meta = self.ds.file_meta

        self.check(
            "FileMetaInformationVersion",
            hasattr(meta, "FileMetaInformationVersion"),
            str(getattr(meta, "FileMetaInformationVersion", "MISSING")),
        )

        self.check(
            "MediaStorageSOPClassUID",
            hasattr(meta, "MediaStorageSOPClassUID"),
            str(getattr(meta, "MediaStorageSOPClassUID", "MISSING")),
        )

        self.check(
            "MediaStorageSOPInstanceUID",
            hasattr(meta, "MediaStorageSOPInstanceUID"),
            str(getattr(meta, "MediaStorageSOPInstanceUID", "MISSING")),
        )

        self.check(
            "TransferSyntaxUID",
            hasattr(meta, "TransferSyntaxUID"),
            str(getattr(meta, "TransferSyntaxUID", "MISSING")),
        )

        self.check(
            "ImplementationClassUID",
            hasattr(meta, "ImplementationClassUID"),
            str(getattr(meta, "ImplementationClassUID", "MISSING")),
        )

    def validate_patient_module(self):
        """Validate Patient Module (mandatory for all IODs)."""
        for tag_name in ["PatientName", "PatientID"]:
            val = getattr(self.ds, tag_name, None)
            has_value = val is not None and str(val).strip() != ""
            self.check(
                tag_name,
                has_value,
                str(val) if has_value else "MISSING or EMPTY",
            )

        # Type 2 tags (must be present, can be empty)
        for tag_name in ["PatientBirthDate", "PatientSex"]:
            self.check(
                f"{tag_name} (Type 2)",
                hasattr(self.ds, tag_name),
                str(getattr(self.ds, tag_name, "MISSING")),
            )

    def validate_study_module(self):
        """Validate General Study Module."""
        mandatory = ["StudyInstanceUID", "StudyDate"]
        for tag_name in mandatory:
            val = getattr(self.ds, tag_name, None)
            has_value = val is not None and str(val).strip() != ""
            self.check(
                tag_name,
                has_value,
                str(val)[:50] if has_value else "MISSING or EMPTY",
            )

    def validate_series_module(self):
        """Validate General Series Module."""
        self.check(
            "SeriesInstanceUID",
            hasattr(self.ds, "SeriesInstanceUID")
            and str(self.ds.SeriesInstanceUID).strip(),
            str(getattr(self.ds, "SeriesInstanceUID", "MISSING"))[:50],
        )

        modality = getattr(self.ds, "Modality", None)
        self.check(
            "Modality",
            modality is not None and str(modality).strip() != "",
            str(modality) if modality else "MISSING",
        )

    def validate_sop_common(self):
        """Validate SOP Common Module."""
        self.check(
            "SOPClassUID",
            hasattr(self.ds, "SOPClassUID"),
            str(getattr(self.ds, "SOPClassUID", "MISSING")),
        )

        self.check(
            "SOPInstanceUID",
            hasattr(self.ds, "SOPInstanceUID"),
            str(getattr(self.ds, "SOPInstanceUID", "MISSING"))[:50],
        )

        # Verify consistency between meta and dataset
        if hasattr(self.ds, "SOPClassUID") and hasattr(
            self.ds.file_meta, "MediaStorageSOPClassUID"
        ):
            self.check(
                "SOP Class Consistency",
                str(self.ds.SOPClassUID)
                == str(self.ds.file_meta.MediaStorageSOPClassUID),
                f"Dataset={self.ds.SOPClassUID} vs Meta={self.ds.file_meta.MediaStorageSOPClassUID}",
            )

    def validate_image_specific(self):
        """Validate image-specific tags."""
        sop_class = str(self.ds.SOPClassUID)

        # Check image-specific tags
        for tag_name in [
            "Rows",
            "Columns",
            "BitsAllocated",
            "BitsStored",
            "HighBit",
            "PixelRepresentation",
            "SamplesPerPixel",
            "PhotometricInterpretation",
        ]:
            val = getattr(self.ds, tag_name, None)
            self.check(
                tag_name, val is not None, str(val) if val is not None else "MISSING"
            )

        # Check pixel data
        self.check(
            "PixelData",
            hasattr(self.ds, "PixelData"),
            "Present" if hasattr(self.ds, "PixelData") else "MISSING",
        )

    def validate_encapsulated_document(self, expected_mime: str):
        """Validate encapsulated document tags."""
        self.check(
            "EncapsulatedDocument",
            hasattr(self.ds, "EncapsulatedDocument"),
            "Present" if hasattr(self.ds, "EncapsulatedDocument") else "MISSING",
        )

        mime = getattr(self.ds, "MIMETypeOfEncapsulatedDocument", None)
        self.check(
            "MIMETypeOfEncapsulatedDocument",
            mime is not None and str(mime) == expected_mime,
            str(mime) if mime else "MISSING",
        )

        self.check(
            "BurnedInAnnotation",
            hasattr(self.ds, "BurnedInAnnotation"),
            str(getattr(self.ds, "BurnedInAnnotation", "MISSING")),
        )

    def validate_all(self, dicom_type: str = "auto"):
        """Run all validations."""
        if not self.load():
            return

        self.validate_file_meta()
        self.validate_patient_module()
        self.validate_study_module()
        self.validate_series_module()
        self.validate_sop_common()

        # Auto-detect type from SOP Class
        if dicom_type == "auto":
            sop = str(self.ds.SOPClassUID)
            if sop in (SOP_SECONDARY_CAPTURE, SOP_VL_PHOTOGRAPHIC) or sop in SOP_NEW_SC_CLASSES:
                dicom_type = "image"
            elif sop == SOP_ENCAPSULATED_PDF:
                dicom_type = "pdf"
            elif sop == SOP_ENCAPSULATED_CDA:
                dicom_type = "cda"
            elif sop == SOP_ENCAPSULATED_STL:
                dicom_type = "stl"

        if dicom_type == "image":
            self.validate_image_specific()
        elif dicom_type == "pdf":
            self.validate_encapsulated_document("application/pdf")
        elif dicom_type == "cda":
            self.validate_encapsulated_document("text/xml")
        elif dicom_type == "stl":
            self.validate_encapsulated_document("model/stl")

    def print_results(self):
        """Print validation results."""
        print(f"\n{'='*60}")
        print(f"DICOM Validation: {self.filepath}")
        print(f"{'='*60}")

        for name, status, detail in self.results:
            symbol = "✅" if status == "PASS" else "❌"
            detail_str = f" — {detail}" if detail else ""
            print(f"  {symbol} {name}{detail_str}")

        print(f"\n  Total: {self.passed + self.failed} checks, "
              f"{self.passed} passed, {self.failed} failed")

        if self.failed == 0:
            print("  🎉 ALL CHECKS PASSED — DICOM Compliant")
        else:
            print(f"  ⚠️  {self.failed} CHECK(S) FAILED")

        return self.failed == 0


def test_server(base_url: str):
    """Test the dicom-converter-api server end-to-end."""
    import subprocess
    from PIL import Image
    import io as io_mod

    print(f"\n{'='*60}")
    print(f"Testing dicom-converter-api server at {base_url}")
    print(f"{'='*60}")

    with tempfile.TemporaryDirectory() as tmpdir:
        # Generate test files
        jpeg_path = os.path.join(tmpdir, "test.jpg")
        png_path = os.path.join(tmpdir, "test.png")
        pdf_path = os.path.join(tmpdir, "test.pdf")

        img = Image.new("RGB", (200, 200), color="red")
        img.save(jpeg_path, "JPEG")
        img.save(png_path, "PNG")

        with open(pdf_path, "wb") as f:
            f.write(b"""%PDF-1.4
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj
3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >> endobj
xref
0 4
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
trailer << /Size 4 /Root 1 0 R >>
startxref
190
%%EOF""")

        all_passed = True

        # Test 1: JPEG → DICOM
        print("\n--- Test 1: JPEG → DICOM ---")
        out_path = os.path.join(tmpdir, "out_jpeg.dcm")
        params = json.dumps({
            "keys": ["PatientName=Test^JPEG", "PatientID=J001", "Modality=XC", "AccessionNumber=JPEG001"]
        })
        result = subprocess.run([
            "curl", "-s", "-o", out_path, "-w", "%{http_code}",
            "-F", f"file=@{jpeg_path}",
            "-F", f"parameters={params}",
            f"{base_url}/api/v1/convert/img2dcm"
        ], capture_output=True, text=True)
        if result.stdout.strip() == "200":
            v = DICOMValidator(out_path)
            v.validate_all("image")
            if not v.print_results():
                all_passed = False
        else:
            print(f"  ❌ HTTP {result.stdout.strip()}")
            all_passed = False

        # Test 2: PNG → DICOM
        print("\n--- Test 2: PNG → DICOM ---")
        out_path = os.path.join(tmpdir, "out_png.dcm")
        params = json.dumps({
            "keys": ["PatientName=Test^PNG", "PatientID=P001"]
        })
        result = subprocess.run([
            "curl", "-s", "-o", out_path, "-w", "%{http_code}",
            "-F", f"file=@{png_path}",
            "-F", f"parameters={params}",
            f"{base_url}/api/v1/convert/img2dcm"
        ], capture_output=True, text=True)
        if result.stdout.strip() == "200":
            v = DICOMValidator(out_path)
            v.validate_all("image")
            if not v.print_results():
                all_passed = False
        else:
            print(f"  ❌ HTTP {result.stdout.strip()}")
            all_passed = False

        # Test 3: PDF → DICOM
        print("\n--- Test 3: PDF → DICOM ---")
        out_path = os.path.join(tmpdir, "out_pdf.dcm")
        params = json.dumps({
            "title": "Test Report",
            "patient_name": "Test^PDF",
            "patient_id": "D001",
            "keys": ["AccessionNumber=PDF001", "Manufacturer=TestHospital"]
        })
        result = subprocess.run([
            "curl", "-s", "-o", out_path, "-w", "%{http_code}",
            "-F", f"file=@{pdf_path}",
            "-F", f"parameters={params}",
            f"{base_url}/api/v1/convert/pdf2dcm"
        ], capture_output=True, text=True)
        if result.stdout.strip() == "200":
            v = DICOMValidator(out_path)
            v.validate_all("pdf")
            if not v.print_results():
                all_passed = False
        else:
            print(f"  ❌ HTTP {result.stdout.strip()}")
            all_passed = False

        # Test 4: Health check
        print("\n--- Test 4: Health Check ---")
        result = subprocess.run([
            "curl", "-s", f"{base_url}/health"
        ], capture_output=True, text=True)
        try:
            health = json.loads(result.stdout)
            is_healthy = health.get("status") == "healthy"
            print(f"  {'✅' if is_healthy else '❌'} Status: {health.get('status')}")
            for dep, status in health.get("dependencies", {}).items():
                print(f"    • {dep}: {status}")
            if not is_healthy:
                all_passed = False
        except json.JSONDecodeError:
            print(f"  ❌ Invalid health response: {result.stdout}")
            all_passed = False

        print(f"\n{'='*60}")
        if all_passed:
            print("🎉 ALL SERVER TESTS PASSED")
        else:
            print("⚠️  SOME TESTS FAILED")
        print(f"{'='*60}")

        return all_passed


def main():
    parser = argparse.ArgumentParser(description="Validate DICOM files from dicom-converter-api")
    parser.add_argument("file", nargs="?", help="DICOM file to validate")
    parser.add_argument("--type", choices=["image", "pdf", "cda", "stl", "auto"],
                        default="auto", help="Type of DICOM file")
    parser.add_argument("--test-server", metavar="URL",
                        help="Test dicom-converter-api server at URL (e.g., http://localhost:8080)")

    args = parser.parse_args()

    if args.test_server:
        success = test_server(args.test_server)
        sys.exit(0 if success else 1)
    elif args.file:
        v = DICOMValidator(args.file)
        v.validate_all(args.type)
        success = v.print_results()
        sys.exit(0 if success else 1)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
